services:
  api:
    image: elysia-api
    build:
      context: ./elysia-api
      dockerfile: Dockerfile
    container_name: elysia-api
    env_file:
      - .env
    ports:
      - "${API_PORT}:4000"
    volumes:
      - ./elysia-api:/elysia-api
      - elysia-api-node-modules:/app/node_modules
    command: bun run dev
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgis/postgis:17-3.5
    platform: linux/amd64
    container_name: elysia-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - elysia-db-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  elysia-db-data:
  elysia-api-node-modules:
