services:
  api:
    image: elysia-api
    build:
      context: ./elysia-api
      dockerfile: Dockerfile
    container_name: elysia-api
    env_file:
      - .env
    ports:
      - "${API_PORT}:4000"
    volumes:
      - ./elysia-api:/elysia-api
    command: bun run dev
    depends_on:
      - db

  db:
    image: postgis/postgis:17-3.5
    platform: linux/amd64
    container_name: elysia-gis
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - elysia-gis:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # web:
  #   image: elysia-web
  #   build:
  #     context: ./elysia-web
  #     dockerfile: Dockerfile
  #   container_name: elysia-web
  #   env_file:
  #     - .env
  #   environment:
  #     NODE_OPTIONS: --max-old-space-size=4096
  #   ports:
  #     - "${WEB_PORT}:3000"
  #   volumes:
  #     - ./elysia-web:/elysia-web
  #     - /elysia-web/node_modules
  #   depends_on:
  #     - api
  #     - db

volumes:
  elysia-gis:
